[project]
name = "specialized-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.49.1",
    "ipykernel>=6.0.0",
    "ipython>=9.6.0",
    "openai>=2.6.1",
]
